import argparse
import pandas as pd
import sys
import random
from pathlib import Path
from pybtex.database import parse_file
from tqdm import tqdm

DROP_LIST = ["InventoryID","Glottocode","ISO6393","LanguageName","SpecificDialect","Marginal","Allophones","Source"]

# Gets the most recent inventories from PHOIBLE
# Input: phoible_loc the location of the phoible directory
#        output_loc  the location to write the inventory list to
# Output: a dictionary of the most recent inventories {glottocode: InventoryID}
def get_inventories(phoible_loc):
    data = pd.read_csv(phoible_loc + "/data/phoible.csv", keep_default_na=False, low_memory=False)
    inventorybib = pd.read_csv(phoible_loc + "/mappings/InventoryID-Bibtex.csv", keep_default_na=False)
    bib = parse_file(phoible_loc + "/data/phoible-references.bib")
    # generate the list of sources we will actually use
    most_recent_inventories = dict()
    for glot in set(data.Glottocode) - set(["NA"]):
        most_recent_inventory = None
        most_recent_year = -1
        for inventory in set(data.InventoryID[data.Glottocode == glot]):
            bibkey = inventorybib.loc[inventorybib["InventoryID"] == inventory, "BibtexKey"].iloc[0]
            if bibkey == "NO SOURCE GIVEN":
                continue
            if "Year" in list(bib.entries[bibkey].fields.keys()):
                year = bib.entries[bibkey].fields['Year']
            elif "Date" in list(bib.entries[bibkey].fields.keys()):
                year = bib.entries[bibkey].fields['Date']
            else:
                print(f"No year or date field for source {bibkey}.", file=sys.stderr)
                year = "0" # if this is the only source, we still want to take it
            if year.startswith("ND") or year == "NULL":
                print(f"ND or NULL year/date for source {bibkey}.", file=sys.stderr)
                year = 0 # if this is the only source, we still want to take it
            year = int(year)
            if (year > most_recent_year):
                most_recent_inventory = inventory
                most_recent_year = year
        most_recent_inventories[glot] = most_recent_inventory
    return most_recent_inventories


# Generates N random samples of languages pulled from around the world
#   There are 20 families chosen from each macroarea (Australia has only 22 families), 
#   and one language is pulled from each family for each sample (1 sample = 120 languages)
# Input: data the pandas dataframe of the PHOIBLE data
#        languages the pandas dataframe of the glottolog languages.csv
#        N the number of samples to generate
# Output: a list of lists of all the samples: [[glo1, glot2, ...], [glot3, glot4, ...], ]
def generate_samples(data, languages, N):
    flanguages = languages[languages.Glottocode.isin(data.Glottocode)]
    # create helper dicts
    macroareas = set(flanguages.Macroarea) - set([''])
    macroareas_families = dict()
    for m in macroareas:
        macroareas_families[m] = list(set(flanguages[flanguages.Macroarea == m].Family_ID))
    family_languages = dict()
    for f in set(flanguages.Family_ID):
        family_languages[f] = list(set(flanguages[flanguages.Family_ID == f].Glottocode))
    # generate samples
    sample_list = []
    for i in range(0,N):
        curr_list = []
        for m in macroareas:
            families = random.sample(macroareas_families[m], 20)
            for f in families:
                curr_list.append(random.choice(family_languages[f]))
        sample_list.append(curr_list)
    return sample_list

            
# Generates a set of phylogenetically diverse samples, and then a dataframe of all
#   segments in PHOIBLE with their counts in all the generated samples
# Input: data the pandas dataframe of the PHOIBLE data
#        samples a list of list of language samples (generated by generated_samples)
#        delta the number of counts to add to every segment (to avoid zeros)
# Output: segments a dict of unique phonemes in PHOIBLE plus a "Counts" column which
#           tallies the counts of the phonemes given the generated segments
#         also writes segments and samples out to file
def calculate_markedness_from_samples(data, samples, delta):
    segments = data.drop(DROP_LIST, axis=1).drop_duplicates()
    segments["Count"] = delta
    print("Tabulating phoneme occurrences in " + str(len(samples)) + " samples...")
    for sample in tqdm(samples, file=sys.stdout):
        for glot in sample:
            for i, row in data[data.Glottocode == glot].drop(DROP_LIST, axis=1).iterrows():
                s_i = segments.index[(segments[list(row.to_dict())] == pd.Series(row.to_dict())).all(axis=1)]
                segments.loc[s_i, "Count"] += 1
    return segments
    

# Calculates a macroarea- and family-weighted count of segments
# Input: data the pandas dataframe of the PHOIBLE data
#        languages the pandas dataframe of the glottolog languages.csv
# Output: segments a dict of unique phonemes in PHOIBLE plus a "Counts" column which
#           tallies the counts, weighted by macroarea and family
def calculate_markedness_from_data(data, languages):
    flanguages = languages[languages.Glottocode.isin(data.Glottocode)]
    macroareas = set(flanguages.Macroarea) - set([''])
    # assign every language family to the macroarea it occurs most frequently in
    macroarea_to_family = dict()
    for m in macroareas:
        macroarea_to_family[m] = []
    for family in set(flanguages.Family_ID) - set([""]):
        most_common_macroarea = None
        most_common_number = 0
        for m in macroareas:
            num_macroarea = flanguages[(flanguages.Family_ID == family) & (flanguages.Macroarea == m)].shape[0]
            if num_macroarea > most_common_number:
                most_common_number = num_macroarea
                most_common_macroarea = m
        macroarea_to_family[most_common_macroarea].append(family)
    # create weighting matrix per family per macroarea
    avg_lgs_per_macroarea = round(flanguages.shape[0] / len(macroareas))
    macroarea_family_weights = dict()
    for m in macroareas:
        macroarea_family_weights[m] = dict()
        num_isolates = flanguages[(flanguages.Family_ID == "") & (flanguages.Macroarea == m)].shape[0]
        num_stocks = num_isolates + len(macroarea_to_family[m])
        # add family weights
        for family in macroarea_to_family[m]:
            num_languages = flanguages[flanguages.Family_ID == family].shape[0]
            macroarea_family_weights[m][family] = avg_lgs_per_macroarea / (num_stocks * num_languages)
        # add isolate weights
        macroarea_family_weights[m][""] = avg_lgs_per_macroarea / num_stocks
    # calculate phoneme markedness
    segments = data.drop(DROP_LIST, axis=1).drop_duplicates()
    segments["Count"] = 0
    print("Tabulating phoneme occurrences weighted by macroarea and family")
    for m in macroarea_family_weights:
        for f in macroarea_family_weights[m]:
            if f == "":
                languages = flanguages[(flanguages.Family_ID == f) & (flanguages.Macroarea == m)].Glottocode
            else:
                languages = flanguages[flanguages.Family_ID == f].Glottocode
            for glot in languages:
                for i, row in data[data.Glottocode == glot].drop(DROP_LIST, axis=1).iterrows():
                    s_i = segments.index[(segments[list(row.to_dict())] == pd.Series(row.to_dict())).all(axis=1)]
                    segments.loc[s_i, "Count"] += macroarea_family_weights[m][f]
    return segments
    

def main(phoible_loc, inventories_loc, languages_loc, segments_loc, stochastic, samples_loc, delta):
    data = pd.read_csv(phoible_loc + "/data/phoible.csv", keep_default_na=False, low_memory=False)
    languages = pd.read_csv(languages_loc, keep_default_na=False, low_memory=False)
    # get the most recent inventories and write to file
    most_recent_inventories = get_inventories(phoible_loc)
    with open(inventories_loc, "w+") as f:
        _ = f.write("Glottocode,Inventory\n")
        for k,v in sorted(most_recent_inventories.items()):
            _ = f.write("%s,%s\n" % (k,v))
    # filter the data according to the inventories actually being used
    data = data[data.InventoryID.isin(most_recent_inventories.values())]
    if stochastic:
        # generate random samples and write to file
        samples = generate_samples(data, languages, 500)
        with open(samples_loc, "w+") as f:
            for sample in samples:
                _ = f.write(",".join(sample) + "\n")
        segments = calculate_markedness_from_samples(data, samples, delta)
        segments.to_csv(segments_loc, index=False)
    else:
        segments = calculate_markedness_from_data(data, languages)
        segments.to_csv(segments_loc, index=False)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-p", "--phoible", help="Path to the PHOIBLE directory. Default is ../phoible/", default=str(Path(__file__).parent / ".." / "phoible"), required=False, type=str
    )
    parser.add_argument(
        "-l", "--languages", help="Location to the glottocode languages.csv file.", default=str(Path(__file__).parent / ".." / "data" / "languages.csv"), required=False, type=str,
    )
    parser.add_argument(
        "-i", "--inventories", help="Location to write the inventories.", default=str(Path(__file__).parent / ".." / "processed" / "inventories.csv"), required=False, type=str,
    )
    parser.add_argument(
        "--segments", help="Location of segment markedness file", default=str(Path(__file__).parent / ".." / "processed" / "segments.csv"), required=False, type=str
    )
    parser.add_argument(
        "--samples", help="Location of samples file. Only used if calculation is --stochastic", default=str(Path(__file__).parent / ".." / "processed" / "samples.txt"), required=False, type=str
    )
    parser.add_argument(
        "-d", "--delta", help="The number of observations to add to the count. Only used if calculation is --stochastic", default=1.0, required=False, type=float
    )
    parser.add_argument(
        "--stochastic", help="Uses randomized sampling to calculate segment markedness. Requires --samples (default: ../processed/samples.txt) and --delta (default: 1.0)", action="store_true", default=False, required=False
    )
    args = parser.parse_args()
    if args.phoible[-1] != "/":
        args.phoible = args.phoible + "/"
    main(args.phoible, args.inventories, args.languages, args.segments, args.stochastic, args.samples, args.delta)